language: cpp
os: linux
compiler: gcc
branches:
  only:
    - dev
    - 18-VTbo-1a
dist: trusty
if: type = pull_request
cache: ccache
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
    update: true
before_install:
  - export PATH="/usr/lib/ccache:$PATH"
  - CC=gcc-7 && CXX=g++-7
  - pwd
install:
  - wget /home/travis http://download.qt.io/official_releases/qt/5.13/5.13.2/qt-opensource-linux-x64-5.13.2.run
  - ls
  - cd /home/travis
  - chmod +x qt-opensource-linux-x64-5.7.0.run
  - ./qt-opensource-linux-x64-5.7.0.run
  - sudo apt-get install mesa-common-dev
jobs:
  include:
    - stage: compile
      before_script: cd LR/07/src
      script:
        - qmake src.pro
        - make
        - make clean && rm Makefile
    - stage: unit tests
      before_script: cd LR/07/tests
      script: echo "Running unit tests..."
          # - stage: Github Release
          #   if: branch = dev
          #   script: skip
          #   deploy:
          #     provider: releases
          #     api_key: "$GITHUB_OAUTH_TOKEN"
          #     skip_cleanup: true
          #     on:
          #       branch: dev
          #       tags: true