language: cpp
os: linux
compiler: gcc
branches:
  only:
    - dev
    - 18-VTbo-1a
dist: trusty
if: type = pull_request
cache: ccache
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
before_install:
  - export PATH="/usr/lib/ccache:$PATH"
  - CC=gcc-7 && CXX=g++-7
install:
  - sudo apt-get install -y qt5-default qttools5-dev-tools
  - sudo apt-get install mesa-common-dev
jobs:
  include:
    - stage: Compile
      before_script: cd LR/07/src
      script:
        - qmake src.pro && make
        - make clean && rm Makefile
    - stage: Unit tests
      before_script: cd LR/07/tests
      script:
        - qmake -project tests.pro && make
        - ./tests.pro
    - stage: Github Release
      if: branch = dev
      script: skip
      deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH_TOKEN"
        skip_cleanup: true
        on:
          branch: dev
          tags: true