language: java
branches:
  only:
  - master
  - 18-VTbo-1b
  - dev
jdk:
- oraclejdk11
sudo: required
dist: trusty
before_install: cd LR/03
addons:
  chrome: stable
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script: mvn install
install:
- wget -N http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
cache:
  directories:
  - "$HOME/.m2"
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
    # Set up git user name and tag this commit
    - git config --local user.name "YOUR GIT USER NAME"
    - git config --local user.email "YOUR GIT USER EMAIL"
    - export TRAVIS_TAG=v.0.0.0.29/04/2020
    - git tag $TRAVIS_TAG
deploy:
  deploy_key:
    secure: PKhzmNeLZ8z/v3aDswCU3nVzlJU3b1kZOtVL7v9DUDMmqMQQLByaF9B0fgrcKbABu8WuJKbb7b/Oea86H/d6xMGtOj8YzSLjpTHmz7UuFufwqf9Obp/QPBrWcX4D4Dp44OBeF+Ok7YCn73Re4zuA58dN/izTyEoRrmLXDi7K+j0T/sstO2aii6H9DDfQwQBqanNkHKZw+yRNDO4zKAWGs3+ZiM6xPSzalH0Tkyx3nPO8nWLo8nsf7GoNL8oiMb1Vdredp7b2wmk1Dj/O1k/wMpj277CMI+wNN9ClL0hgXDYclAN0lttPAn2kgNFLdJFGCkfqxGxAGN3nEXakQwV9cJbdLpMyRDVv/ZEmg4k7sa4hvwRnfJXNS1o0258PAJ32ljsVhiSZYrIQyyqLGkRHXimxbbuyi4ltq4hxJqAva5zv6BckqHoJwQWja//NtEcDn7OzUZRfFXreGhWjMEnm/qtP4aSzR7bspJmrsKY4gR01Du7f4+QLxExon7vRG4h/AUymPVKt4vZQxMhlBBFID8kaucLqF9/hIf4sT3xGz18A+gLyHcYmROr1A1wgkqW7nShEUWKSuYCRWrNqJ8ZeiFqhgC5dInF9tbyyQF2oQOZTJ/lzaSTFuWroYo7XEeunjURdUQmoCGaK3Z2BgskCl4yKb7x5DN7E5EnVyccap0E=
  skip_cleanup: true
  provider: releases
  prerelease: true	
  name: 18-VTbo-1b
  file: 
     - /home/travis/build/Students-of-the-city-of-Kostroma/trpo_automation/LR/03/target/Selen-0.1-jar-with-dependencies.jar
     - /home/travis/build/Students-of-the-city-of-Kostroma/trpo_automation/LR/03/Repository.xml
  on:
    branch: dev
    condition: $TRAVIS_COMMIT_MESSAGE == *"release"*