language: cpp
os: linux
compiler: gcc
branches:
  only:
    - dev
    - 18-VTbo-1a
dist: trusty
if: type = pull_request
cache: ccache
before_install:
  - export PATH="/usr/lib/ccache:$PATH"
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
install:
  - sudo apt-get install gcc-7 g++-7
  - sudo apt-get install -y qt5-default qttools5-dev-tools
addons:
  apt:
    update: true
jobs:
  include:
    - stage: compile
      before_script: cd LR/07/src
      script:
        - qmake "CONFIG+=debug" src.pro
        - make
        - make clean && rm Makefile
    - stage: unit tests
      before_script: cd LR/07/Tests
      script: echo "Running unit tests..."
          # - stage: Github Release
          #   if: branch = dev
          #   script: skip
          #   deploy:
          #     provider: releases
          #     api_key: "$GITHUB_OAUTH_TOKEN"
          #     skip_cleanup: true
          #     on:
          #       branch: dev
          #       tags: true


# install:
#   - sudo apt-get install -y qt5-default qttools5-dev-tools #install necessary Qt files

# script:
#   - qmake "CONFIG+=debug" SimpleQtTest.pro #we gonna compile for actual program
#   - make
#   - ./SimpleQtTest #run actual program
