# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- 18-ISbo-2a

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    architecture: 'x64'

- script: | 
    pip install coverage
  displayName: 'Install libraries'

- script: | 
    coverage run -m unittest discover
    coverage xml APIgoogle.py client.py Validation.py
  displayName: 'Run tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: 'coverage.xml'
    testRunTitle: 'Publish test results for Python $(python.version)'

